### ISSUE TITLE
doc: added PR and Issue templates

### ISSUE THREAD

**Issue by vedant-jain03** [vedant-jain03/certificate-generator#10]
## Description
We need PR and issue templates!

**Comment by at-the-vr** [comment]
Hi Vedant, Atharva this side, I was wondering if I can start working on this Issue. I will be referring to [@eddiehub-hacktoberfest-practice](https://github.com/eddiejaoude/eddiehub-hacktoberfest-practice) for the respective templates.

**Comment by vedant-jain03** [comment]
> Hi Vedant, Atharva this side, I was wondering if I can start working on this Issue. I will be referring to [@eddiehub-hacktoberfest-practice](https://github.com/eddiejaoude/eddiehub-hacktoberfest-practice) for the respective templates.

Cool, go ahead!

**Comment by at-the-vr** [comment]
HI Vedant, I have covered all of possible Issues and PR Templates. I am providing a link to my fork, I would like if you could try it [fork-certificate-generator](https://github.com/itsEobard2025/certificate-generator).
All the changes are in the .github folder and you can definitely try raising an Issue or making a PR on this fork.
Please let me know if it requires further changes 😄
Thanks

**Comment by at-the-vr** [comment]
Hey Vedant, sorry to disturb you at this hour, but I wanted to know your feedback on this.
Really don't wanna drag it too long. Incase it sounds/looks confusing please let me know, I want to get this fix available to all Other Contributors as well so they don't get confused here and there 😇

**Comment by vedant-jain03** [comment]
@itsEobard2025 sorry for late reply, kindly raise a PR for the review!

**Comment by at-the-vr** [comment]
Hey @vedant-jain03 , could you let me know if the PR #25 is valid ? Could use some feedback
