### ISSUE TITLE
UI: instruction popup

### ISSUE THREAD

**Issue by vedant-jain03** [vedant-jain03/certificate-generator#11]
## Description

The Instruction popup UI is not looking good. We need to update that!

![Screenshot from 2022-09-30 09-46-20](https://user-images.githubusercontent.com/76901313/193189304-804be7fd-5bef-4821-8d25-42ad1aa9fe01.png)

**Comment by lmas3009** [comment]
Can i work on this

**Comment by vedant-jain03** [comment]
> Can i work on this

Sure, go ahead!

**Comment by lmas3009** [comment]
I just updated with PR
