### ISSUE TITLE
fix: Template does not appear according to the number of available templates

### ISSUE THREAD

**Issue by gunalirezqimauludi** [vedant-jain03/certificate-generator#35]
### Description

for now there are 11 total templates, but only 3 templates appear in the application, this problem occurs because the id attribute naming in the template does not match, resulting in a configuration.

fixed bug "template name conflict in the html id selector which causes all templates to not appear" and add new template certificate

### Screenshots

![template](https://user-images.githubusercontent.com/25346009/197307228-bb460bc1-2261-4183-88d3-f0a9598c8401.png)
![template-2](https://user-images.githubusercontent.com/25346009/197307233-f16ffa92-c722-4d3f-8b78-64a65dcd08f2.png)

### Want to contribute ?

Yes

**Comment by vedant-jain03** [comment]
@gunalirezqimauludi the new version is not deployed yet, will release after Hacktoberfest

You can test all templates in development mode!

**Comment by gunalirezqimauludi** [comment]
@vedant-jain03 sorry, at first I wanted to try to contribute to adding a new certificate template, and during development the template that appeared did not match, therefore I assumed that this was a bug, and I tried to make improvements and I have made a 'pull request' [#30](https://github.com/vedant-jain03/certificate-generator/pull/30)
