### ISSUE TITLE
feat: add more themes

### ISSUE THREAD

**Issue by vedant-jain03** [vedant-jain03/certificate-generator#7]
## Description

Initially, we have 3 templates for certificates. We potentially need 3 more different templates. Kindly share the template before working on it!

**Comment by CDPhu** [comment]
Hello, I would like to work on this for Hacktoberfest 2022, and I can add more than three if that's ok with you.

**Comment by vedant-jain03** [comment]
@LostButton go ahead!

**Comment by CDPhu** [comment]
Please check the templates if they are ok, and if anything of them needs modification.

**Comment by CDPhu** [comment]
Tenplates should be fixed now

**Comment by vedant-jain03** [comment]
> Tenplates should be fixed now

Hey @LostButton sorry for late response, I will test your PR and will let you know my reviews ASAP!

cc @yashikajotwani12

**Comment by CDPhu** [comment]
Template 7 should be fixed.
