### ISSUE TITLE
feat: CI/CD workflows for PRs

### ISSUE THREAD

**Issue by vedant-jain03** [vedant-jain03/certificate-generator#9]
## Description

We need basic CI/CD workflows for PR.

**Comment by opensourceally** [comment]
Want to take this. Please assign this to me.

**Comment by vedant-jain03** [comment]
> Want to take this. Please assign this to me.

Cool, go ahead @opensourceally !

**Comment by vedant-jain03** [comment]
@opensourceally what is the progress status?
